/**
 * Schema preparation for OpenAI structured output.
 *
 * Transforms kickstartDS Design System JSON Schemas into a format compatible
 * with OpenAI's structured output (`response_format: json_schema`).
 *
 * The OpenAI API has constraints that vanilla JSON Schemas don't:
 * - No `const` keyword → replaced with `type__<value>` string discriminators
 * - No unsupported keywords (`format`, `$id`, `$schema`, `minItems`, etc.)
 * - `additionalProperties: false` required on every object
 * - All properties must be listed in `required`
 * - Limits on total property count (< 5000) and enum values (< 1000)
 *
 * Pure functions — no framework dependencies. Usable from API routes,
 * MCP servers, n8n nodes, or browser-side React components.
 */

// json-schema-traverse ships a CJS default export.
// In ESM we may receive `{ default: fn }` or `fn` directly depending on the
// bundler / runtime, so we normalise here.
import _schemaTraverse from "json-schema-traverse";
const schemaTraverse: typeof _schemaTraverse =
  typeof (_schemaTraverse as any).default === "function"
    ? (_schemaTraverse as any).default
    : _schemaTraverse;

type TraverseCallback = _schemaTraverse.Callback;

// ─── Static data ──────────────────────────────────────────────────────

/**
 * Keywords that OpenAI's structured output does not support and must be
 * stripped before sending the schema.
 */
export const UNSUPPORTED_KEYWORDS = [
  "format",
  "minItems",
  "maxItems",
  "minimum",
  "maximum",
  "examples",
  "default",
  "$id",
  "$schema",
] as const;

/**
 * Properties that are layout / styling concerns and should generally not
 * be generated by AI (they are set at the CMS level instead).
 */
export const DEFAULT_PROPERTIES_TO_DROP = [
  "backgroundColor",
  "backgroundImage",
  "spotlight",
  "textColor",
] as const;

/**
 * Component names that are available for AI content generation.
 */
export const SUPPORTED_COMPONENTS = [
  "blog-teaser",
  "business-card",
  "contact",
  "content-nav",
  "cta",
  "divider",
  "downloads",
  "faq",
  "features",
  "gallery",
  "headline",
  "hero",
  "image-story",
  "image-text",
  "info-table",
  "logos",
  "mosaic",
  "page",
  "section",
  "split-even",
  "split-weighted",
  "stats",
  "teaser-card",
  "testimonials",
  "text",
  "video-curtain",
] as const;

/**
 * Maps parent component names to the property key that holds their
 * sub-component arrays (e.g. `downloads` → `download`).
 */
export const SUB_COMPONENT_MAP: Record<string, string> = {
  downloads: "download",
  faq: "questions",
  features: "feature",
  gallery: "images",
  logos: "logo",
  mosaic: "tile",
  stats: "stat",
  testimonials: "testimonial",
} as const;

// ─── Helpers ──────────────────────────────────────────────────────────

/**
 * Extract the component name from a JSON Schema `$id` URI.
 * E.g. `"http://…/hero.schema.json"` → `"hero"`.
 */
export function getSchemaName(schemaId: string): string {
  return (schemaId && schemaId.split("/").pop()?.split(".").shift()) || "";
}

// ─── Types ────────────────────────────────────────────────────────────

/** Options for `prepareSchemaForOpenAi`. */
export interface PrepareSchemaOptions {
  /**
   * Number of sections to generate.
   * Sets both `minItems` and `maxItems` on the section array.
   */
  sections?: number;
  /**
   * Whitelist of component names to include.
   * Defaults to `SUPPORTED_COMPONENTS`.
   */
  allowedComponents?: string[];
  /**
   * Property names to strip from every component schema.
   * Defaults to `DEFAULT_PROPERTIES_TO_DROP`.
   */
  propertiesToDrop?: string[];
}

/** The OpenAI-compatible schema envelope. */
export interface OpenAiSchemaEnvelope {
  name: string;
  strict: boolean;
  schema: Record<string, any>;
}

/** Validation diagnostics returned alongside the prepared schema. */
export interface SchemaValidation {
  totalProperties: number;
  maxDepth: number;
  enumValueCount: number;
  warnings: string[];
}

/** Full result of `prepareSchemaForOpenAi`. */
export interface PreparedSchema {
  /** Schema envelope ready to pass to OpenAI `response_format.json_schema`. */
  envelope: OpenAiSchemaEnvelope;
  /**
   * Map of component type name → its original (pre-transformation) schema.
   * Used later by `processOpenAiResponse` to merge defaults.
   */
  schemaMap: Record<string, Record<string, any>>;
  /** Validation diagnostics. */
  validation: SchemaValidation;
}

// ─── Core API ─────────────────────────────────────────────────────────

/**
 * Transform a dereffed page schema into an OpenAI-compatible structured
 * output schema.
 *
 * This is the main entry point — it runs all 13 transformation passes
 * that were previously embedded in the PrompterComponent.
 *
 * @param pageSchema - The fully dereferenced page JSON Schema from
 *   `@kickstartds/ds-agency-premium/page/page.schema.dereffed.json`.
 * @param options - Optional configuration.
 * @returns The prepared schema envelope + component schema map.
 */
export function prepareSchemaForOpenAi(
  pageSchema: Record<string, any>,
  options: PrepareSchemaOptions = {}
): PreparedSchema {
  const {
    sections,
    allowedComponents = SUPPORTED_COMPONENTS as unknown as string[],
    propertiesToDrop = DEFAULT_PROPERTIES_TO_DROP as unknown as string[],
  } = options;

  // Mutable map that gets populated during traversal
  const schemaMap: Record<string, Record<string, any>> = {};

  // Validation accumulators
  const allProperties = new Set<string>();
  let maxDepth = 0;
  let enumValueCount = 0;
  const warnings: string[] = [];

  // ── Pass 0: Collect component schemas by type const ─────────────
  const collectSchemas: TraverseCallback = (schema) => {
    if (
      schema.properties &&
      schema.properties.type &&
      schema.properties.type.const
    ) {
      schemaMap[schema.properties.type.const] = structuredClone(schema);
    }
  };

  // Run on the *original* schema before cloning
  schemaTraverse(pageSchema, collectSchemas);

  // Clone so we don't mutate the caller's object
  const clonedSchema = structuredClone(pageSchema);

  // ── Structural pruning ──────────────────────────────────────────
  delete clonedSchema.properties.header;
  delete clonedSchema.properties.footer;

  if (sections !== undefined) {
    clonedSchema.properties.section.minItems = sections;
    clonedSchema.properties.section.maxItems = sections;
  }

  // Add type consts to sub-component arrays
  const sectionItems =
    clonedSchema.properties.section?.items?.properties?.components?.items;
  if (sectionItems && sectionItems.anyOf) {
    for (const componentSchema of sectionItems.anyOf) {
      const componentName = getSchemaName(componentSchema.$id);
      const arrayKey = SUB_COMPONENT_MAP[componentName];
      if (
        arrayKey &&
        componentSchema.properties?.[arrayKey]?.items?.properties
      ) {
        componentSchema.properties[arrayKey].items.properties.type = {
          const: arrayKey,
        };
      }
    }
  }

  // ── Traverse-based transformation passes ────────────────────────

  const addTypeConsts: TraverseCallback = (schema) => {
    if (schema && schema.anyOf) {
      schema.anyOf.forEach((component: any) => {
        if (component.$id) {
          const componentName = getSchemaName(component.$id);
          if (
            allowedComponents.includes(componentName) &&
            !component.properties?.type
          ) {
            component.properties.type = { const: componentName };
          }
        }
      });
    }
  };

  const filterComponents: TraverseCallback = (schema) => {
    if (schema && schema.anyOf) {
      schema.anyOf = schema.anyOf.filter((component: any) => {
        return (
          component.properties?.type &&
          component.properties.type.const &&
          allowedComponents.includes(component.properties.type.const)
        );
      });
    }
  };

  const deleteConsts: TraverseCallback = (
    schema,
    jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    parentKeyword,
    parentSchema
  ) => {
    if (schema.const && parentKeyword === "properties" && parentSchema) {
      const propName = jsonPtr.split("/").pop();
      if (propName === "type") {
        const type: Record<string, any> = { properties: {} };
        type.properties[`type__${schema.const}`] = {
          type: "string",
          title: "Type of component",
          description: `A field always being set to the value '${schema.const}'`,
        };
        parentSchema.properties = {
          ...type.properties,
          ...parentSchema.properties,
        };
      }
      if (propName) {
        delete parentSchema.properties[propName];
      }
    }
  };

  const removeImageFormatProperties: TraverseCallback = (
    schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    _parentSchema,
    _keyIndex
  ) => {
    if (schema.format === "image" || schema.format === "video") {
      delete schema.format;
    }
  };

  const removeIconProperties: TraverseCallback = (
    _schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    parentSchema,
    keyIndex
  ) => {
    if (keyIndex === "icon" && parentSchema?.properties?.[keyIndex]) {
      delete parentSchema.properties[keyIndex];
    }
  };

  const removeUnsupportedProperties: TraverseCallback = (
    _schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    parentSchema,
    keyIndex
  ) => {
    if (
      keyIndex &&
      typeof keyIndex === "string" &&
      propertiesToDrop.includes(keyIndex) &&
      parentSchema?.properties?.[keyIndex]
    ) {
      delete parentSchema.properties[keyIndex];
    }
  };

  const removeUnsupportedKeywords: TraverseCallback = (schema) => {
    for (const key of UNSUPPORTED_KEYWORDS) {
      if (Object.prototype.hasOwnProperty.call(schema, key)) {
        delete schema[key];
      }
    }
  };

  const removeEmptyObjects: TraverseCallback = (
    schema,
    _jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    _parentKeyword,
    parentSchema,
    keyIndex
  ) => {
    if (
      schema.type === "object" &&
      schema.properties &&
      !Object.keys(schema.properties).length &&
      keyIndex &&
      parentSchema?.properties?.[keyIndex]
    ) {
      delete parentSchema.properties[keyIndex];
    }
  };

  const denyAdditionalProperties: TraverseCallback = (schema) => {
    if (schema.type === "object") {
      schema.additionalProperties = false;
    }
  };

  const makeRequired: TraverseCallback = (schema) => {
    if (schema.type === "object" && schema.properties) {
      schema.required = Object.keys(schema.properties);
    }
  };

  // ── Validation passes ───────────────────────────────────────────

  const collectProperties: TraverseCallback = (
    _schema,
    jsonPtr,
    _rootSchema,
    _parentJsonPtr,
    parentKeyword
  ) => {
    if (
      jsonPtr &&
      parentKeyword === "properties" &&
      !allProperties.has(jsonPtr)
    ) {
      allProperties.add(jsonPtr);
    }
  };

  const countDepth: TraverseCallback = (_schema, jsonPtr) => {
    const depth = jsonPtr.split("/properties/").length;
    maxDepth = Math.max(depth, maxDepth);
  };

  const countEnums: TraverseCallback = (schema) => {
    if (schema.enum) {
      enumValueCount += schema.enum.length;
    }
  };

  // ── Execute all passes ──────────────────────────────────────────
  [
    addTypeConsts,
    filterComponents,
    deleteConsts,
    removeImageFormatProperties,
    removeIconProperties,
    removeUnsupportedProperties,
    removeUnsupportedKeywords,
    removeEmptyObjects,
    denyAdditionalProperties,
    makeRequired,
    collectProperties,
    countDepth,
    countEnums,
  ].forEach((fn) => {
    schemaTraverse(clonedSchema, fn);
  });

  // ── Collect warnings ────────────────────────────────────────────
  if (allProperties.size > 5000) {
    warnings.push(
      `Property count (${allProperties.size}) exceeds OpenAI limit of 5000.`
    );
  }
  if (enumValueCount > 1000) {
    warnings.push(
      `Enum value count (${enumValueCount}) exceeds OpenAI limit of 1000.`
    );
  }

  return {
    envelope: {
      name: "page_response",
      strict: true,
      schema: clonedSchema,
    },
    schemaMap,
    validation: {
      totalProperties: allProperties.size,
      maxDepth,
      enumValueCount,
      warnings,
    },
  };
}

/**
 * Derive a single-component OpenAI-ready schema from the full page schema.
 *
 * This is useful for generating content for one specific component type
 * (e.g. "hero", "faq") without needing the full page envelope.
 *
 * @param pageSchema - The fully dereferenced page schema.
 * @param componentName - Name of the component (e.g. "hero").
 * @returns A single-component schema envelope, or `null` if the component
 *   is not found.
 */
export function getComponentPresetSchema(
  pageSchema: Record<string, any>,
  componentName: string
): OpenAiSchemaEnvelope | null {
  const { envelope, schemaMap } = prepareSchemaForOpenAi(pageSchema, {
    allowedComponents: [componentName, "section"],
    sections: 1,
  });

  // Extract just the component schema from the section's anyOf
  const sectionItems =
    envelope.schema?.properties?.section?.items?.properties?.components?.items;
  if (!sectionItems?.anyOf) return null;

  const match = sectionItems.anyOf.find((s: any) => {
    const typeKey = Object.keys(s.properties || {}).find((k) =>
      k.startsWith("type__")
    );
    return typeKey === `type__${componentName}`;
  });

  if (!match) return null;

  // Return a standalone schema for just that component
  return {
    name: `${componentName.replace(/-/g, "_")}_section`,
    strict: true,
    schema: match,
  };
}

/**
 * Return the list of component names available for AI generation.
 */
export function listAvailableComponents(): string[] {
  return [...SUPPORTED_COMPONENTS];
}
