declare module "@kickstartds/page.schema.json/lib/page/typing" {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {SectionProps} from "@kickstartds/base/lib/section/typing";
import type {SeoProps} from "@kickstartds/seo.schema.json/lib/seo/typing";

/**
 * Collection of sections (with their contents) to render on the page
 */
export type Sections = SectionProps[];
/**
 * Toggle default floating header behaviour set in global settings
 */
export type ToggleFloating = boolean;
/**
 * Toggle default inverted header behaviour set in global settings
 */
export type ToggleInverted = boolean;
/**
 * Override for logo
 */
export type Logo = string;
/**
 * Toggle default inverted footer behaviour set in global settings
 */
export type ToggleInverted1 = boolean;
/**
 * Override for logo
 */
export type Logo1 = string;
/**
 * CSS custom property overrides to be included in the global styles
 */
export type LocalCSSCustomPropertyOverrides = string;

/**
 * Abstracts a page concept into JSON schema
 */
export interface PageProps {
  section?: Sections;
  header?: Header;
  footer?: Footer;
  token?: LocalCSSCustomPropertyOverrides;
  /**
   * Referenced component SeoProps
   */
  seo: SeoProps;
}
/**
 * Header settings for the page
 */
export interface Header {
  floating?: ToggleFloating;
  inverted?: ToggleInverted;
  logo?: Logo;
}
/**
 * Footer settings for the page
 */
export interface Footer {
  inverted?: ToggleInverted1;
  logo?: Logo1;
}

}
      