/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether the business card content is centered.
 */
export type Centered = boolean;
/**
 * A headline or main topic for the business card, such as a job title or department.
 */
export type Topic = string;
/**
 * The physical or mailing address displayed on the business card.
 */
export type Address = string;
/**
 * A list of contact methods for the person or business (e.g., email, phone, website).
 */
export type ContactInformation = {
  /**
   * Label describing the contact method (e.g., 'Email', 'Phone').
   */
  label: string;
  /**
   * Icon name or identifier representing the contact method.
   */
  icon?: string;
  /**
   * URL or link for the contact method, if applicable.
   */
  url?: string;
}[];
/**
 * A list of action buttons shown on the business card.
 */
export type Buttons = {
  /**
   * Text label for the link.
   */
  label: string;
  /**
   * URL the link points to.
   */
  url: string;
}[];

/**
 * Business card component representing an individual's or company's contact information and branding.
 */
export interface BusinessCardProps {
  centered?: Centered;
  image?: BackgroundImage;
  logo?: CompanyLogo;
  topic?: Topic;
  address?: Address;
  avatar?: Avatar;
  contact?: ContactInformation;
  buttons?: Buttons;
}
/**
 * A background or feature image displayed on the business card.
 */
export interface BackgroundImage {
  /**
   * URL of the background image shown on the business card.
   */
  src: string;
  /**
   * Alternative text describing the background image.
   */
  alt?: string;
}
/**
 * The logo of the company or organization displayed on the business card.
 */
export interface CompanyLogo {
  /**
   * URL of the company or organization logo.
   */
  src: string;
  /**
   * Alternative text describing the logo.
   */
  alt?: string;
  /**
   * URL to the company's website or landing page.
   */
  url?: string;
}
/**
 * A profile image or avatar representing the person on the business card.
 */
export interface Avatar {
  /**
   * URL of the person's avatar or profile image.
   */
  src: string;
  /**
   * Alternative text describing the avatar.
   */
  alt?: string;
}
